### ISSUE TITLE
実装: VRMのリップシンク

### ISSUE THREAD

**Issue by junyatakechi** [toshi-kundesu/Vsinger-HaishinRoom#1]
# 要件
- [ ] VRMのアバターのリップが動くように
- [ ] PCのデフォルトのオーディオデバイスを入力にする。

**Comment by toshi-kundesu** [comment]
# 調べたこと
- [[VRMアバターをマイク音量から口パクさせる【リップシンク】](https://bibinbaleo.hatenablog.com/entry/2020/07/29/220135)](https://bibinbaleo.hatenablog.com/entry/2020/07/29/220135)
